import React, { useState } from 'react';
import { jsPDF } from 'jspdf';

const Posts = ({ posts }) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [sortOrder, setSortOrder] = useState('desc');

  const handleSearchChange = (e) => {
    setSearchTerm(e.target.value);
  };

  const handleSortToggle = () => {
    setSortOrder((prevOrder) => (prevOrder === 'desc' ? 'asc' : 'desc'));
  };

  const handlePrint = (post) => {
    const doc = new jsPDF('p', 'pt', 'a4');
    doc.setFontSize(14);
  
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
  
    const headerHeight = 60;
    const footerHeight = 60;
    const contentHeight = pageHeight - headerHeight - footerHeight;
  
    // Header
    doc.setFontSize(18);
    doc.text('Forum Post', 20, 40);
  
    // Content
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(`Title: ${post.title}`, 40, 100);
    doc.text(`Content:`, 40, 140);
    doc.setFont('times', 'italic');
    doc.setFontSize(12);
    doc.text(post.content, 40, 160, { maxWidth: pageWidth - 80 });
    doc.setFont('times', 'normal');
    doc.setFontSize(14);
    doc.text(`Author: ${post.user.name}`, 40, 240);
  
    // Comments
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 255);
    doc.text('Comments:', 40, 280);
    doc.setFontSize(12);
    let commentY = 320;
    post.comments.forEach((comment) => {
      doc.text(`- ${comment.content}`, 40, commentY, { maxWidth: pageWidth - 80 });
      commentY += 20;
    });
  
    // Footer
    doc.setFontSize(12);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by Forum App', 20, pageHeight - 30);
  
    // Save PDF
    doc.save(`${post.title}.pdf`);
  };
  

  const filteredPosts = posts.filter((post) =>
    post.title.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const sortedPosts = filteredPosts.sort((a, b) => {
    if (sortOrder === 'asc') {
      return a.likes.length - b.likes.length;
    } else {
      return b.likes.length - a.likes.length;
    }
  });

  return (
    <div className="posts">
      <div className="search-bar">
        <input
          type="text"
          value={searchTerm}
          onChange={handleSearchChange}
          placeholder="Search by title"
        />
      </div>
      <button className="sort-button" onClick={handleSortToggle}>
        Sort {sortOrder === 'asc' ? 'Asc' : 'Desc'}
      </button>
      {sortedPosts.length > 0 ? (
        sortedPosts.map((post) => (
          <div key={post.id} className="post">
            <h2>{post.title}</h2>
            <p>{post.content}</p>
            <p className="author">Author: {post.user.name}</p>
            <div className="comments-section">
              <h3>Comments:</h3>
              {post.comments.length > 0 ? (
                <ul className="comments-list">
                  {post.comments.map((comment) => (
                    <li key={comment.id} className="comment">
                      {comment.content}
                    </li>
                  ))}
                </ul>
              ) : (
                <p>No comments yet.</p>
              )}
            </div>
            <p className="likes">Likes: {post.likes.length}</p>
            <button className="print-button" onClick={() => handlePrint(post)}>
              Print
            </button>
          </div>
        ))
      ) : (
        <p>No posts found.</p>
      )}
    </div>
  );
};

export default Posts;
